app/api/urls.py
from django.urls import path

from .views import CreateCustomTransactionView, UpdateTransactionStatusView, ReportView, FetchTransactionsView
from . import views
app_name = 'api'

urlpatterns = [
    path('transaction/<id>', UpdateTransactionStatusView.as_view(), name='transaction'),
    path('report/<date>', ReportView.as_view(), name='report'),
    path('fetch/', FetchTransactionsView.as_view(), name='fetch'),
    path('create_custom/',
         CreateCustomTransactionView.as_view(), name='create_custom'),
    path('token/', views.CreateTokenView.as_view(), name='token'),

]

app/app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('authentication.urls')),
    path('', include('nordigen.urls')),
    path('api/', include('api.urls'))
]

app/authentication/urls.py
from django.urls import path

from .views import login_user, logout_user, register_user

app_name = 'authentication'

urlpatterns = [
    path('register/', register_user, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
]

app/core/urls.py
from django.urls import path

from .views import dashboard, fetch_transactions, main_page, overview

app_name = 'core'

urlpatterns = [
    path('', main_page, name='home'),
    path('dashboard/', dashboard, name='dashboard'),
    path('mock_fetch/', fetch_transactions, name='mock_fetch'),
    path('overview/<id>', overview, name='overview'),
]

app/authentication/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm


class RegisterUserForm(UserCreationForm):
    email = forms.EmailField(required=False)
    nordigen_user_id = forms.CharField(required=False)

    class Meta:
        model = get_user_model()
        fields = ('username', 'email',
                  'nordigen_user_id', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control my-1'
        self.fields['username'].widget.attrs['placeholder'] = '#'
        self.fields['email'].widget.attrs['class'] = 'form-control my-1'
        self.fields['email'].widget.attrs['placeholder'] = '#'
        self.fields['nordigen_user_id'].widget.attrs['class'] = 'form-control my-1'
        self.fields['nordigen_user_id'].widget.attrs['placeholder'] = '#'
        self.fields['password1'].widget.attrs['class'] = 'form-control my-1'
        self.fields['password1'].widget.attrs['placeholder'] = 'form-control my-1'
        self.fields['password2'].widget.attrs['class'] = 'form-control my-1'
        self.fields['password2'].widget.attrs['placeholder'] = 'form-control my-1'


class LoginUserForm(AuthenticationForm):
    # class Meta:
    #     model = get_user_model()
    #     fields = ('username', 'password')
    #     widgets = {
    #         'username': forms.TextInput(attrs={'class': 'form-control my-1'}),
    #         'password': forms.PasswordInput(attrs={'class': 'form-control my-1'}),
    #     }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['class'] = 'form-control my-1'
        self.fields['username'].widget.attrs['placeholder'] = '#'
        self.fields['password'].widget.attrs['class'] = 'form-control my-1'
        self.fields['password'].widget.attrs['placeholder'] = 'form-control my-1'

app/authentication/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import redirect, render

from .forms import LoginUserForm, RegisterUserForm

# Create your views here.


def register_user(request):
    if request.method == 'POST':
        form = RegisterUserForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            messages.success(request, 'Registration successful.')
            return redirect("core:home")
        messages.error(request, "Error while registering.")
    form = RegisterUserForm()
    return render(request, 'authentication/register.html', context={'form': form})


def login_user(request):
    if request.method == 'POST':
        form = LoginUserForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, "Success!")
                return redirect('core:home')
        messages.error(request, 'Invalid credentials')
    form = LoginUserForm()
    return render(request, 'authentication/login.html', context={'form': form})


def logout_user(request):
    logout(request)
    return redirect('core:home')

app/authentication/templates/authentication/login.html
{% extends 'core/base.html' %}

{% block banner %}
Login
{% endblock banner %}
{% block path %}
Login
{% endblock path %}
{% block content %}

<div class="container-fluid container-xxl pt-3 text-white background-secondary" style="max-width: 30rem;">
    <form method='POST'>
        {% csrf_token %}
        {% for field in form %}
        <div class="form-floating mb-3">
            {{ field }}
            {{ field.label_tag }}
        </div>

        {% for error in field.errors %}
        <div class="alert alert-danger" role="alert"><strong>{{ error }}</strong></div>
        {% endfor %}
        {% endfor %}
        <div class='text-center mt-4'>
            <button type="submit" class="btn bg-blue w-25">Login</button>
        </div>
    </form>
    <div class='text-center mt-4'>
        <div>Don't have an account?</div>
        <a href={% url 'authentication:register' %} class="">Register</a>
    </div>
</div>

{% endblock %}

app/authentication/templates/authentication/register.html
{% extends 'core/base.html' %}

{% block banner %}
Register
{% endblock banner %}
{% block path %}
Register
{% endblock path %}
{% block content %}

<div class="container-fluid container-xxl pt-3 text-white background-secondary" style="max-width: 30rem;">
    <form method='POST'>
        {% csrf_token %}
        {% for field in form %}
        <div class="form-floating mb-3">
            {{ field }}
            {{ field.label_tag }}
        </div>

        {% for error in field.errors %}
        <div class="alert alert-danger" role="alert"><strong>{{ error }}</strong></div>
        {% endfor %}
        {% endfor %}
        <div class="text-center mt-4">
            <button type="submit" class="btn bg-blue w-25">Register</button>
        </div>
    </form>
    <div class='text-center mt-4'>
        <a href={% url 'core:home' %} class="">Go back</a>
    </div>
</div>

{% endblock %}