app/api/urls.py
from django.urls import path

from .views import CreateCustomTransactionView, UpdateTransactionStatusView, ReportView, FetchTransactionsView
from . import views
app_name = 'api'

urlpatterns = [
    path('transaction/<id>', UpdateTransactionStatusView.as_view(), name='transaction'),
    path('report/<date>', ReportView.as_view(), name='report'),
    path('fetch/', FetchTransactionsView.as_view(), name='fetch'),
    path('create_custom/',
         CreateCustomTransactionView.as_view(), name='create_custom'),
    path('token/', views.CreateTokenView.as_view(), name='token'),

]

app/app/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('authentication.urls')),
    path('', include('nordigen.urls')),
    path('api/', include('api.urls'))
]

app/authentication/urls.py
from django.urls import path

from .views import login_user, logout_user, register_user

app_name = 'authentication'

urlpatterns = [
    path('register/', register_user, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
]

app/core/urls.py
from django.urls import path

from .views import dashboard, fetch_transactions, main_page, overview

app_name = 'core'

urlpatterns = [
    path('', main_page, name='home'),
    path('dashboard/', dashboard, name='dashboard'),
    path('mock_fetch/', fetch_transactions, name='mock_fetch'),
    path('overview/<id>', overview, name='overview'),
]

app/nordigen/urls.py
from django.urls import path

from .views import fetch_data

app_name = 'nordigen'

urlpatterns = [
    path('fetch/', fetch_data, name='fetch'),
]

app/core/models.py
import datetime

from django.contrib import admin
from django.contrib.auth.models import (AbstractBaseUser, BaseUserManager,
                                        PermissionsMixin)
from django.db import models


class UserManager(BaseUserManager):
    def create_user(self, username, password=None, **kwargs):
        if not username:
            raise ValueError('User must have a username')
        user = self.model(
            username=username,
            **kwargs,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, password=None):
        user = self.create_user(username, password)
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=255, unique=True)
    email = models.EmailField(max_length=255, null=True, blank=True)
    nordigen_user_id = models.CharField(max_length=255, null=True, blank=True)

    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)

    USERNAME_FIELD = 'username'

    objects = UserManager()


class Transaction(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    id = models.BigAutoField(primary_key=True)
    booking_date = models.DateField()
    value_date = models.DateField()
    transaction_amount = models.FloatField()
    debtor_name = models.TextField()
    info = models.TextField(default="", blank=True)
    ignore = models.BooleanField(default=False)

    CATEGORY_CHOICES = [
        ('Groceries', 'Groceries'),
        ('Food', 'Food'),
        ('Travel', 'Travel'),
        ('Clothing', 'Clothing'),
        ('Transfer', 'Transfer'),
        ('Entertainment', 'Entertainment'),
        ('Other', 'Other'),
    ]
    category = models.CharField(
        choices=CATEGORY_CHOICES, default='Other', max_length=20)
    VALUE_CHOICES = [
        ('SP', 'Spendings'),
        ('IN', 'Income'),
        ('RE', 'Returned'),
    ]
    value = models.CharField(choices=VALUE_CHOICES, default='SP', max_length=2)

    report = models.ForeignKey(
        'MonthlyReport', on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return f"{self.debtor_name}, {self.transaction_amount}"

    @property
    def month_year(self):
        return f"{self.value_date.month:02d}" + '-' + str(self.value_date.year)

    def save(self, *args, **kwargs):
        date = datetime.date(self.value_date.year, self.value_date.month, 1)
        report, created = MonthlyReport.objects.get_or_create(
            user=self.user,
            date=date,
        )
        self.report = report

        self.set_category()
        self.set_value()

        super().save(*args, **kwargs)

    def set_category(self):
        if self.transaction_amount > 0:
            return
        category_list = {
            'Groceries': [
                'ZABKA', 'ZAPPKA', 'CARREFOUR', 'LIDL', 'VEMAT', 'ORLEN', 'CHATA', 'KIOSK', 'BIEDRONKA', 'KAUFLAND',
                'ALDI', 'BALTONA'
            ],
            'Food': [
                'MC DON', 'KFC', 'MCDONALDS', 'BARABOO', 'EATS', 'PYSZNE', 'GLODNY', 'PIZZ', 'SALAD', 'KIM CHI',
                'MAKARONSKI', 'STODOLA', 'STOLOWKA', 'PASTWISKO', 'GAST', 'RAGU', 'BURG', 'CLUB', 'PASIBUS',
                'UPMENU', 'PROPORCJA', 'KONKRET MARTA'
            ],
            'Travel': [
                'JAKDOJADE', 'BILKOM', 'LIM', 'DOTT', 'TRIP', 'BOLT', 'INTERCITY', 'URBANCARD'
            ],
            'Clothing': [
                'ZARA', 'ASOS', 'ZALANDO', 'SPORT-SHOP'
            ],
            'Entertainment': [
                'BILA', 'CINEMA', 'MULTIKINO', 'HELIOS', 'NETFLIX', 'GRAVITACJA'
            ],
            'Transfers': [
                'PRZELEW ŚRODKÓW', 'REVOLUT'
            ]}
        for category, names in category_list.items():
            for name in names:
                if name in self.debtor_name.upper():
                    self.category = category
                    return

    def set_value(self):
        if self.transaction_amount > 0 and self.value not in ['IN', 'RE']:
            self.value = 'IN'


class MonthlyReport(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # Day set to always be 01
    date = models.DateField()

    total_spendings = models.FloatField(default=0, null=True, blank=True)
    total_income = models.FloatField(default=0, null=True, blank=True)
    number_of_transactions = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.user} - {self.date.strftime('%B %Y')}"

    @property
    def previous(self):
        previous = MonthlyReport.objects.filter(
            date__lt=self.date, user=self.user).order_by('date').last()
        return previous

    def sync(self):
        returned = Transaction.objects.filter(
            report=self, value='RE', ignore=False).aggregate(models.Sum('transaction_amount'))['transaction_amount__sum'] or 0
        spent = Transaction.objects.filter(
            report=self, value='SP', ignore=False).aggregate(models.Sum('transaction_amount'))['transaction_amount__sum'] or 0
        self.total_spendings = -returned - spent

        self.total_income = Transaction.objects.filter(
            report=self, value='IN', ignore=False).aggregate(models.Sum('transaction_amount'))['transaction_amount__sum'] or 0
        self.number_of_transactions = Transaction.objects.filter(
            report=self).aggregate(models.Count('transaction_amount'))['transaction_amount__count'] or 0
        self.save()

app/nordigen/forms.py
import datetime

from django import forms
from django.core.exceptions import ValidationError


class FetchForm(forms.Form):
    today = datetime.date.today()
    month = forms.IntegerField(required=False,
                               widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': '#', 'value': today.month}))
    year = forms.IntegerField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': '#', 'value': today.year}))

    def clean_month(self):
        today = datetime.date.today()
        month = self.cleaned_data.get('month', None)
        if month is None:
            return month
        year = self.cleaned_data.get('year')
        if month > 12 or month <= 0 or (year == today.year and month > today.month):
            raise ValidationError("The month is not valid!")

        return month

    def clean_year(self):
        today = datetime.date.today()
        year = self.cleaned_data['year']
        if year > today.year:
            raise ValidationError("The year is not valid")

        return year

app/core/views.py
import datetime
import json
import os
from calendar import monthrange

from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.db import models
from django.shortcuts import HttpResponse, redirect, render

from app.settings import BASE_DIR
from app.tasks import get_transactions

from .models import MonthlyReport, Transaction

# Create your views here.


def main_page(request):
    return redirect('core:dashboard')


@login_required()
def dashboard(request):
    date = datetime.date(datetime.date.today().year,
                         datetime.date.today().month, 1)
    report_list = MonthlyReport.objects.filter(
        user=request.user).order_by('-date')
    latest, created = MonthlyReport.objects.get_or_create(
        date=date, user=request.user)
    return render(request, 'core/dashboard.html', context={'report_list': report_list, 'latest': latest})


@login_required()
def fetch_transactions(request):
    # get_transactions_by_month.delay(
    #     request.user.id, 1, 2023, "8cf965fa-6ed0-494d-ad5c-cfa5f660ee55")
    file_path = os.path.join(BASE_DIR, 'result.json')
    f = open(file_path)
    data = json.load(f)['booked']
    f.close()

    for transaction in data:
        if transaction.get('debtorName'):
            info = transaction.get('remittanceInformationUnstructured', "")
        else:
            info = ""

        booking_date = datetime.datetime.strptime(
            transaction.get('bookingDate'), "%Y-%m-%d").date()
        value_date = datetime.datetime.strptime(
            transaction.get('valueDate'), "%Y-%m-%d").date()

        values = {
            'user': get_user_model().objects.get(id=request.user.id),
            'booking_date': booking_date,
            'value_date': value_date,
            'transaction_amount': float(transaction.get(
                'transactionAmount')['amount']),
            'debtor_name': transaction.get('debtorName', transaction.get(
                'remittanceInformationUnstructured')),
            'info': info
        }

        Transaction.objects.update_or_create(
            id=transaction.get('transactionId'),
            defaults=values
        )

    # Update stats on monthly reports
    for report in MonthlyReport.objects.all():
        report.total_spendings = Transaction.objects.filter(
            report=report, transaction_amount__lt=0).aggregate(models.Sum('transaction_amount'))['transaction_amount__sum'] or 0
        report.total_income = Transaction.objects.filter(
            report=report, transaction_amount__gte=0).aggregate(models.Sum('transaction_amount'))['transaction_amount__sum'] or 0
        report.number_of_transactions = Transaction.objects.filter(
            report=report).aggregate(models.Count('transaction_amount'))['transaction_amount__count'] or 0
        report.save()
    return render(request, 'core/home.html')


@login_required()
def overview(request, id=None):
    report = MonthlyReport.objects.get(id=id)
    if report.previous is not None:
        spendings_bar = report.total_spendings / \
            (report.previous.total_spendings + 1) * 100
        income_bar = report.total_income / \
            (report.previous.total_income + 1) * 100
        transactions_bar = report.number_of_transactions / \
            (report.previous.number_of_transactions + 1) * 100
    else:
        spendings_bar = 100
        income_bar = 100
        transactions_bar = 100

    outgoing = Transaction.objects.filter(
        value='SP', report=report).order_by('-value_date', 'debtor_name')
    income = Transaction.objects.filter(
        value='IN', report=report).order_by('-value_date', 'debtor_name')
    returns = Transaction.objects.filter(
        value='RE', report=report).order_by('-value_date', 'debtor_name')

    report_spendings = -round(Transaction.objects.filter(
        models.Q(value='SP') | models.Q(value='RE'),
        report=report,
        ignore=False,
    ).aggregate(models.Sum('transaction_amount'))['transaction_amount__sum'] or 0, 2)

    categories = {
        'groceries': -round(Transaction.objects.filter(
            ignore=False,
            value='SP',
            category='Groceries',
            report=report
        ).aggregate(models.Sum('transaction_amount'))['transaction_amount__sum'] or 0, 2),
        'food': -round(Transaction.objects.filter(
            ignore=False,
            value='SP',
            category='Food',
            report=report
        ).aggregate(models.Sum('transaction_amount'))['transaction_amount__sum'] or 0, 2),
        'groceries': -round(Transaction.objects.filter(
            ignore=False,
            value='SP',
            category='Groceries',
            report=report
        ).aggregate(models.Sum('transaction_amount'))['transaction_amount__sum'] or 0, 2),
        'travel': -round(Transaction.objects.filter(
            ignore=False,
            value='SP',
            category='Travel',
            report=report
        ).aggregate(models.Sum('transaction_amount'))['transaction_amount__sum'] or 0, 2),
        'clothing': -round(Transaction.objects.filter(
            ignore=False,
            value='SP',
            category='Clothing',
            report=report
        ).aggregate(models.Sum('transaction_amount'))['transaction_amount__sum'] or 0, 2),
        'transfers': -round(Transaction.objects.filter(
            ignore=False,
            value='SP',
            category='Transfers',
            report=report
        ).aggregate(models.Sum('transaction_amount'))['transaction_amount__sum'] or 0, 2),
        'entertainment': -round(Transaction.objects.filter(
            ignore=False,
            value='SP',
            category='Entertainment',
            report=report
        ).aggregate(models.Sum('transaction_amount'))['transaction_amount__sum'] or 0, 2),
        'other': -round(Transaction.objects.filter(
            ignore=False,
            value='SP',
            category='Other',
            report=report
        ).aggregate(models.Sum('transaction_amount'))['transaction_amount__sum'] or 0, 2),
    }

    dates = [report.date + datetime.timedelta(days=x) for x in range(
        monthrange(report.date.year, report.date.month)[1])]
    daily_spendings = []
    for i, date in enumerate(dates):
        daily_spendings.append(-round(Transaction.objects.filter(
            user=request.user,
            value='SP',
            report=report,
            value_date=date,
            ignore=False
        ).aggregate(models.Sum('transaction_amount'))['transaction_amount__sum'] or 0, 2))
    timeline = []
    for i in range(0, len(daily_spendings), 3):
        timeline.append(sum(daily_spendings[i:i+3]))

    context = {
        'income': income,
        'returns': returns,
        'outgoing': outgoing,
        'report': report,
        'spendings_bar': spendings_bar,
        'income_bar': income_bar,
        'transactions_bar': transactions_bar,
        'report_spendings': report_spendings,
        'categories': categories,
        'timeline': timeline
    }

    return render(request, 'core/overview.html', context=context)


def update_report(id):
    transaction = Transaction.objects.get(id=id)
    report = transaction.report

    report.total_spendings = round(-Transaction.objects.filter(
        models.Q(value='SP') | models.Q(value='RE'),
        report=report
    ).aggregate(models.Sum('transaction_amount'))['transaction_amount__sum'], 2)

    report.total_income = Transaction.objects.filter(
        report=report,
        value='IN'
    ).aggregate(models.Sum('transaction_amount'))['transaction_amount__sum'] or 0

    report.number_of_transactions = Transaction.objects.filter(
        report=report
    ).aggregate(models.Count('transaction_amount'))['transaction_amount__count'] or 0

    report.save()

app/core/templates/core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <link rel="stylesheet" href={% static 'base-styles.css' %} />
</head>

<body>

    <nav id='navbar' class="navbar navbar-dark fixed-top">
        <div class="container-fluid mx-2">
            <div>
                <a class="navbar-brand mx-2 fs-2" href={% url 'core:home' %}>Finances</a>
            </div>

            <span class="navbar-text">
                {% if user.is_authenticated %}
                <a class="fs-4 text-decoration-none" href={% url 'authentication:logout' %}>Logout</a>
                {% else %}
                <a class="fs-4 text-decoration-none" href={% url 'authentication:login' %}>Login</a>
                {% endif %}
            </span>
        </div>
    </nav>


    <div id='content' class="content">

        {% comment %} Banner {% endcomment %}
        <div class="banner bg-secondary pt-1">
            <div class="container-fluid text-center text-light fs-4 background-secondary m-2">
                <div class="text-start text-nowrap">
                    {% block banner %}
                    {% endblock banner %}
                </div>
                {% if messages %}
                <div class="position-absolute w-75 mx-auto" style="left: 0; right: 0; z-index: 100;">
                    {% for message in messages %}
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
                    <div style='margin-bottom: 0'
                        class="mx-auto alert alert-warning alert-dismissible fade show fs-5 p-1" role="alert">
                        {{message}}
                        <button style='padding: 0.6rem' type="button" class="btn-close" data-bs-dismiss="alert"
                            aria-label="Close"></button>
                    </div>
                    {% else %}
                    <div style='margin-bottom: 0'
                        class="mx-auto alert alert-success alert-dismissible fade show fs-5 p-1" role="alert">
                        {{message}}
                        <button style='padding: 0.6rem' type="button" class="btn-close" data-bs-dismiss="alert"
                            aria-label="Close"></button>
                    </div>
                    {% endif %}
                    {% endfor %}
                </div>
                {% endif %}
            </div>
        </div>

        {% comment %} Breadcrumb {% endcomment %}
        {% if not latest %}
        <div class="container-fluid py-2">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb mb-0 py-3">
                    <li class="breadcrumb-item "><a class='blue' href={% url 'core:home' %}>Home</a></li>
                    <li class="breadcrumb-item active text-white" aria-current="page">
                        {% block path %}
                        {% endblock path %}
                    </li>
                </ol>
            </nav>
        </div>
        {% endif %}

        {% block content %}{% endblock content %}

    </div>

    {% block modals %}{% endblock modals %}

</body>

{% block scripts %}{% endblock scripts %}

</html>

app/core/templates/core/dashboard.html
{% extends 'core/base.html' %}
{% load abs %}

{% block banner %}
Dashboard
{% endblock banner %}
{% block path %}Dashboard{% endblock path %}

{% block content %}
<section id='quick-action'>
    <div class="row g-5 justify-content-center">
        <div class="col-11 col-xl-4">
            <div class="bg-secondary text-light fs-4 card h-100">
                <div class='card-header d-flex justify-content-between'>
                    <div>This month:</div>
                    <a class='fw-bold text-end w-25' style='color: #51cbee' href="/overview/{{latest.id}}">&#8250;</a>
                </div>
                <div class="card-body">
                    <div class="d-flex justify-content-between align-items-end">
                        <div>Number of transactions:</div>
                        <div style='color: #51cbee' class='fs-1'>{{latest.number_of_transactions}}</div>
                    </div>
                    <hr>
                    <div>
                        <div class="d-flex justify-content-between align-items-end">
                            <div>Spendings:</div>
                            <div style='color: #51cbee' class='fs-3'>{{latest.total_spendings|floatformat:1|abs }}
                            </div>
                        </div>
                        <div class="d-flex justify-content-between align-items-end">
                            <div>Income:</div>
                            <div style='color: #51cbee' class='fs-3'>{{latest.total_income|floatformat:1 }}</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-11 col-xl-4">
            <div class="bg-secondary text-light fs-4 card h-100">
                <div class='card-header d-flex justify-content-between'>
                    <div>Fetch data by month:</div>
                    <button id="btnFetch" style='color: #51cbee' type="submit"
                        class="text-button fw-bold text-end w-25">&#8250;</button>
                </div>
                <div class="card-body">
                    <div class="">
                        <label for="id_month">Month:</label>
                        <input type="number" max="12" min="1" name="month" class="form-control fs-5" placeholder="#"
                            value="{{latest.date.month}}" id="id_month">
                    </div>
                    <div class="mb-3">
                        <label for="id_year">Year:</label>
                        <input type="number" name="year" class="form-control fs-5" placeholder="#" value="2023"
                            required="" id="id_year">
                    </div>

                </div>
            </div>
        </div>

    </div>
</section>

<section id='history' class="mt-2 container-xxl">
    <div class='fs-1 fw-bold text-light pb-3 ps-3'>
        History
    </div>
    <div class="row g-3">
        {% for report in report_list %}
        <div class="col-6 col-md-4 col-lg-3">
            <a href="/overview/{{report.id}}" class="bg-blue" style='heght: 130px; display: block'>
                <div class='bg-secondary h-100 py-2 px-2'>
                    <div class='fs-3 fw-bold text-light'>
                        {{ report.date|date:"F" }}

                    </div>
                    <div class='fs-5 fw-bold text-light'>
                        {{report.date.year}}
                    </div>
                    <div class='fs-4 text-light mx-1' style='text-align: right'>
                        -{{report.total_spendings|floatformat:0}}
                    </div>
                    <hr class='m-0' style='opacity: 0.8'>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</section>


<script>
    const btnFetch = document.getElementById('btnFetch');
    const month = document.getElementById('id_month');
    const year = document.getElementById('id_year');
    const CSRF_TOKEN = '{{ csrf_token }}';

    btnFetch.addEventListener('click', function () {

        content = {
            'month': month.value,
            'year': year.value
        }

        fetch('http://127.0.0.1:8000/api/fetch/', {
            method: "POST",
            headers: {
                'X-CSRFToken': CSRF_TOKEN,
                "Content-Type": "application/json"
            },
            body: JSON.stringify(content)
        })
            .then(response => response.json())
            .then(data => {
                if (data.status == 'success') {
                    location.reload();
                }
                // console.log(data);
            })
            .catch(error => console.log(error));
    })
</script>


{% endblock content %}

app/core/templates/core/home.html
{% extends 'core/base.html' %}

{% block content %}
{% if user.is_authenticated %}
<div class="fs-1" style="text-align: center; margin-bottom:20px">Welcome, {{user.username}}</div>
{% endif %}


<div class="container border shadow border-primary rounded p-4 pt-3 w-50">
    
    
</div>

{% endblock  %}

app/core/templates/core/old_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid m-1">
          <a class="navbar-brand" href={% url 'core:home' %}>Home</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <a href={% url 'nordigen:fetch' %}>Fetch</a>
            </ul>
            <span class="navbar-text">
              {% if user.is_authenticated %}
              <a class="fs-5 text-decoration-none mx-2" href={% url 'authentication:logout' %}>Logout</a>
              {% else %}
              <a class="fs-5 text-decoration-none mx-2" href={% url 'authentication:login' %}>Login</a>
              {% endif %}
          
            </span>
          </div>
        </div>
      </nav>
    <div class="container mt-3 w-50">
        {% if messages %}
        {% for message in messages %}
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}
            <div class="alert alert-danger" role="alert">
                {{message}}
            </div>
            {% else %}
            <div class="alert alert-success" role="alert">
                {{message}}
            </div>
        
        {% endif %}
        {% endfor %}
        {% endif %}
      </div>

        {% block content %}
        {% endblock content %}



</body>
</html>